name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v.0.7.0
        with:
          ssh-private-key: ${{ secrects.SHH_key }}

      - name: Deploy via scp
        run: |
          scp -r -o StrictHostKeyChecking=no ./ azureuser@20.11.20.171:/home/azureuser/web-page-simple-docker

      - name: Build and restart Docker
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@20.11.20.171 << 'EOF'
            cd /home/azureuser/web-page-simple-docker
            sudo docker build -t hilman/app-docker .
            sudo docker stop $(sudo docker ps -q)
            sudo docker run -d -p 80:80 hilman/app-docker
          EOF
